apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-application-deployment
  labels:
    app: express-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-application
  template:
    metadata:
      labels:
        app: express-application
    spec:
      containers:
      - name: express-application
        image: razzaksr/express-api:latest
        ports:
        - containerPort: 1234
        env:
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: express-application-service
spec:
  type: NodePort
  selector:
    app: express-application
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234
      nodePort: 32750
